### PR TITLE
code

### PR DESCRIPTION
**Pull request by abhisheksharma13**
hey
could you pl. send me the complete code of you myntra tinder app.
pl. help .
thanks 
send--> abhi13101993@gmail.com

### CODE REVIEW

**Comment by syllogismos** [comment]
@abhisheksharma13 are you new to github? The code is right there. Also please don't spam. You created a pull request and asked me here and then asked me the same question in some other issue completely unrelated to this code. https://github.com/syllogismos/facebook-link-prediction/issues/3#issuecomment-84352235 

Here is the zip file of the complete code https://github.com/syllogismos/MyntraTinder/archive/master.zip

Thanks for your interest :dancer: 
Good luck :+1:

**Comment by abhisheksharma13** [comment]
yes am new here...
srry won't spam 
thnks a lot fr the code

**Comment by abhisheksharma13** [comment]
Project contains lots n lots of errors :(

**Comment by syllogismos** [comment]
I used Android Studio to build. Those errors are probably because of not setting up gradle properly or something.. I was able to build it successfully. You can even get the apk from here.. http://syllogismos.github.io/blog/2014/09/04/tinder-like-android-app-that-showcases-products-from-a-fashion-website/

**Comment by abhisheksharma13** [comment]
KKK BRO. WAS IMPORTING IT ON ECLIPSE WOULD TRY DOING THE SAME IN ANDROID STUDIO

**Pull request closed without merging**
